server:
  port: 8081
welcome:
  message: "Service is down"
login:
  adminEnabled: false
app:
  jwtSecret: "sadfasdf"
  jwtExpirationMs: "88899"
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/a_jjfood
    username: root2
    password: Basappa123)
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:mem:dcbapp
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: pass

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: off
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    enabled: true